version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: razilahamed/backend:${BUILD_NUMBER}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: razilahamed/frontend:${BUILD_NUMBER}
    ports:
      - "3000:80"
